#ifndef __CONSTANTS_HPP__
#define __CONSTANTS_HPP__

enum PlayerColor {PLC_RED, PLC_YELLOW, PLC_BLUE, PLC_GREEN, PLC_NOCOLOR};
enum StandCardType {SC_EMPTY, SC_FORTRESS, SC_CHEST1, SC_CHEST2, SC_CHEST3, SC_TREASURE};
enum NoStandCardType {NSC_ARRUP, NSC_ARRDOWN, NSC_ARRRIGHT, NSC_ARRLEFT, NSC_MANEATER};
enum CardType {EMPTY, FORTRESS, CHEST1, CHEST2, CHEST3, TREASURE, ARRUP, ARRDOWN, ARRRIGHT, ARRLEFT, MANEATER};

enum {CARDS_EMPT = 79, CARDS_ARRUP = 4, CARDS_ARRDOWN = 4, CARDS_ARRRIGHT = 4, CARDS_ARRLEFT = 4, CARDS_MEA = 3, CARDS_FRT = 3, CARDS_CH1 = 5, CARDS_CH2 = 5, CARDS_CH3 = 5, CARDS_TRS = 1};
enum {BOAR_SIZE = 12};

#endif