#ifndef __CONSTANTS_HPP__
#define __CONSTANTS_HPP__

enum PlayerColor {
	PLC_RED = 0, PLC_YELLOW = 1, PLC_BLUE = 2, PLC_GREEN = 3, PLC_NOCOLOR = 4
};

enum StandCardType {
	SC_EMPTY = 0, SC_FORTRESS = 10, SC_CHEST1 = 1, SC_CHEST2 = 2, SC_CHEST3 = 3, SC_TREASURE = 4
};

enum NoStandCardType {
	NSC_ARRUP = 5, NSC_ARRDOWN = 6, NSC_ARRRIGHT = 7, NSC_ARRLEFT = 8, NSC_MANEATER = 9
};

enum CardType {
	EMPTY = 0, FORTRESS = 10, CHEST1 = 1, CHEST2 = 2, CHEST3 = 3, TREASURE = 4, 
	ARRUP = 5, ARRDOWN = 6, ARRRIGHT = 7, ARRLEFT = 8, MANEATER = 9
};

enum {
	CARDS_EMPT = 79, CARDS_ARRUP = 4, CARDS_ARRDOWN = 4, CARDS_ARRRIGHT = 4, CARDS_ARRLEFT = 4, 
	CARDS_MEA = 3, CARDS_FRT = 3, CARDS_CH1 = 5, CARDS_CH2 = 5, CARDS_CH3 = 5, CARDS_TRS = 1
};

enum {
	BOARD_SIZE = 13, CARD_TYPES = 11
};

enum {
	ACT_MOVE_PIRATE = 1, ACT_MOVE_SHIP = 2, ACT_FIN_GAME = 3
};

enum MoveTypes {
	MOVE_UP = 11, MOVE_DOWN = 22, MOVE_LEFT = 33, MOVE_RIGHT = 44
};

#endif